networks:
  laravel_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/laravel
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8000:80
    depends_on:
      - app
    container_name: laravel_nginx
    networks:
      - laravel_network

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/laravel
    # depends_on:
    #   - db
    container_name: laravel_app
    networks:
      - laravel_network

  # db:
  #   image: mysql:9.0
  #   restart: always
  #   volumes:
  #     - ./tmp/db:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: appdb
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - 3306:3306
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  #   container_name: laravel_db
  #   networks:
  #     - laravel_network

